name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install
        run: |
          chmod +x gradlew
          git clone https://github.com/icarohs7/unox-buildsrc buildSrc
      - name: Build
        run: |
          ./gradlew -Pcoverage clean build jacocoTestReport -x lint --stacktrace
      - name: Send coverage to codecov
        run: bash <(curl -s https://codecov.io/bash)